import type { Metadata } from "next";
import Link from "next/link";
import { GUIDED_ESTIMATES as GE } from "@/components/marketing/guidedEstimates";
import { ESTIMATE_TRIPS } from "@/components/marketing/content";

/**
 * /product/guided-estimates — SITEMAP.md.
 *
 * ITS JOB IS ONE QUESTION: can Price2Book help me quote work remotely
 * without publishing instant prices? The answer is yes, and the page is
 * built to prove it rather than assert it.
 *
 * A SIBLING OF GUIDED PRICING, NOT A CONSOLATION PRIZE. A contractor who
 * shows no prices and reviews every job is using the product as designed.
 * Nothing on this page may frame the estimate path as what happens when
 * instant pricing "fails" — the two are choices, made service by service.
 *
 * EVERYTHING NUMERIC COMES FROM THE CAPTURE. The services, the photograph
 * requests, the worked example and the review queue are read from
 * `guidedEstimates.ts`, which is generated by a read-only capture and
 * drift-checked in the build. The temptation on a page like this is to
 * invent a tidy estimate workflow; the fixture is what stops that.
 *
 * WHAT IT MAY NOT SAY. That software determines the estimate — a contractor
 * sets every one. That photographs are interpreted — they are collected and
 * looked at by a person. That every job can be quoted remotely — the last
 * section exists precisely to deny that.
 */
export const metadata: Metadata = {
  title: "Guided Estimates — quote the work without publishing a price",
  description:
    "The customer answers your guided questions and sends the details and photographs you asked for. You review the scope and set the estimate. You do not have to display prices online to use Price2Book.",
  alternates: { canonical: "/product/guided-estimates" },
};

export const dynamic = "force-dynamic";

const SHELL = "mx-auto max-w-[1440px] px-5 lg:px-[88px]";

export default function GuidedEstimatesPage() {
  const ex = GE.example;

  return (
    <main>
      {/* ── the claim ─────────────────────────────────────────────────── */}
      <section className={`${SHELL} pb-10 pt-12 lg:pb-12 lg:pt-[76px]`}>
        <div className="mb-5 flex items-center gap-2.5">
          <div className="h-0.5 w-[26px] bg-p2b-accent" />
          <span className="text-[11px] font-semibold uppercase tracking-[0.09em] text-p2b-accent lg:text-xs">
            Guided Estimates
          </span>
        </div>
        <h1 className="max-w-[19ch] text-[40px] font-bold leading-[1.04] tracking-[-0.022em] lg:text-[64px]">
          You don’t have to show prices online to use Price2Book.
        </h1>
        <p className="mt-6 max-w-[70ch] text-[17px] leading-[1.55] text-p2b-ink-warm lg:text-xl">
          The customer still walks the guided questions. They still describe the job in their own
          words, still answer what they can see, and still send the photographs you asked for. Then
          it comes to you, and <strong className="font-semibold text-p2b-ink">you</strong> set the
          estimate.
        </p>
      </section>

      {/* ── the estimate trip: the reason to care ─────────────────────── */}
      <section className="border-t border-p2b-line bg-p2b-canvas-alt py-14 lg:py-[72px]">
        <div className={SHELL}>
          <h2 className="max-w-[26ch] text-[28px] font-bold leading-[1.12] tracking-[-0.022em] lg:text-[40px]">
            {ESTIMATE_TRIPS.headline}
          </h2>
          <p className="mt-6 max-w-[74ch] text-[17px] leading-[1.6] text-p2b-ink-warm">
            {ESTIMATE_TRIPS.lead}
          </p>

          <div className="mt-10 grid gap-8 lg:grid-cols-2 lg:gap-12">
            {[ESTIMATE_TRIPS.before, ESTIMATE_TRIPS.after].map((seq, i) => (
              <div key={seq.label}>
                <div className="text-[11px] font-bold uppercase tracking-[0.06em] text-p2b-muted-soft">
                  {seq.label}
                </div>
                <ol className="mt-4 flex flex-col gap-0">
                  {seq.steps.map((step, n) => (
                    <li key={step} className="flex gap-4">
                      <div className="flex flex-col items-center">
                        <span
                          className={`mt-[7px] h-1.5 w-1.5 shrink-0 rounded-full ${
                            i === 1 ? "bg-p2b-accent" : "bg-p2b-faint"
                          }`}
                        />
                        {n < seq.steps.length - 1 ? (
                          <span className="w-px flex-1 bg-p2b-line-dash" />
                        ) : null}
                      </div>
                      <span
                        className={`pb-3 text-[16px] leading-[1.45] ${
                          i === 1 ? "text-p2b-ink" : "text-p2b-muted"
                        }`}
                      >
                        {step}
                      </span>
                    </li>
                  ))}
                </ol>
              </div>
            ))}
          </div>

          <p className="mt-8 max-w-[74ch] border-l-2 border-p2b-line-dash pl-5 text-[16px] leading-[1.6] text-p2b-muted">
            {ESTIMATE_TRIPS.caveat}
          </p>
        </div>
      </section>

      {/* ── what the customer is actually asked ───────────────────────── */}
      {ex ? (
        <section className={`${SHELL} border-t border-p2b-line py-14 lg:py-[72px]`}>
          <div className="grid gap-10 lg:grid-cols-12 lg:gap-12">
            <div className="lg:col-span-5">
              <h2 className="max-w-[22ch] text-[28px] font-bold leading-[1.15] tracking-[-0.022em] lg:text-[36px]">
                They send what you would have driven over to look at.
              </h2>
              <p className="mt-5 text-[17px] leading-[1.6] text-p2b-ink-warm">
                A request for “a photo” collects nothing useful. The questions name the thing the
                office needs to see, in the words a homeowner can act on — and the estimate waits
                until they have sent it.
              </p>
              <p className="mt-5 text-[16px] leading-[1.6] text-p2b-muted">
                Across the catalog the product asks for{" "}
                <strong className="font-semibold text-p2b-ink">{GE.photos.distinctLabels}</strong>{" "}
                different photographs by name. Nothing reads them. They are collected, and a person
                looks at them.
              </p>
              <p className="mt-7 text-[15px] leading-[1.5] text-p2b-muted-soft">
                A real service, its real question and the photographs it actually requires.
              </p>
            </div>

            <div className="lg:col-span-7">
              <div className="rounded-[3px] border border-p2b-line bg-white px-6 py-6 lg:px-8 lg:py-7">
                <div className="text-[11px] font-bold uppercase tracking-[0.06em] text-p2b-muted-soft">
                  {ex.serviceName}
                </div>
                <p className="mt-4 text-[18px] font-semibold leading-[1.35] text-p2b-ink lg:text-[19px]">
                  {ex.prompt}
                </p>
                <div className="mt-4 inline-flex items-center rounded-[3px] border border-p2b-line bg-p2b-canvas-alt px-4 py-2 text-[15px] text-p2b-ink">
                  {ex.answer}
                </div>

                <div className="mt-7 border-t border-p2b-line pt-6">
                  <div className="text-[11px] font-bold uppercase tracking-[0.06em] text-p2b-muted-soft">
                    Then it asks for
                  </div>
                  <ul className="mt-4 flex flex-col gap-3">
                    {ex.photoLabels.map((l) => (
                      <li key={l} className="flex items-start gap-3">
                        <span aria-hidden className="mt-[9px] h-1.5 w-1.5 shrink-0 rounded-full bg-p2b-accent" />
                        <span className="text-[15px] leading-[1.45] text-p2b-ink-warm lg:text-base">{l}</span>
                      </li>
                    ))}
                  </ul>
                  <p className="mt-5 text-[15px] leading-[1.55] text-p2b-muted">
                    {ex.blocksBooking
                      ? "No price is released here. The job goes to you with the answers and the photographs attached."
                      : "The price is already set; these help the technician arrive prepared."}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
      ) : null}

      {/* ── you set the number ────────────────────────────────────────── */}
      <section className="border-t border-p2b-line bg-p2b-canvas-alt py-14 lg:py-[72px]">
        <div className={SHELL}>
          <h2 className="max-w-[24ch] text-[28px] font-bold leading-[1.15] tracking-[-0.022em] lg:text-[38px]">
            It arrives as a job to price, not a price to approve.
          </h2>
          <p className="mt-5 max-w-[74ch] text-[17px] leading-[1.6] text-p2b-ink-warm">
            Submitted estimates land in a review queue with the customer’s answers and their
            photographs together in one place. You price the work. The customer sees your number and
            accepts it. No software decides the amount at any point.
          </p>

          <div className="mt-9 grid gap-5 sm:grid-cols-3">
            {[
              {
                k: `${GE.remoteQuote.services}`,
                v: "services already running this way",
                d: `across ${GE.remoteQuote.categories.length} categories`,
              },
              {
                k: `${GE.remoteQuote.withoutPublishedPrice}`,
                v: "of them publish no price at all",
                d: "the storefront lists the work, not a number",
              },
              {
                k: `${GE.photos.blocking}`,
                v: "answers that hold the price back",
                d: "until the photographs are in",
              },
            ].map((s) => (
              <div key={s.v} className="rounded-[3px] border border-p2b-line bg-white px-6 py-5">
                <div className="text-[32px] font-bold leading-none tracking-[-0.02em] text-p2b-ink">
                  {s.k}
                </div>
                <div className="mt-3 text-[15px] font-semibold leading-[1.35] text-p2b-ink">{s.v}</div>
                <div className="mt-1.5 text-[14px] leading-[1.4] text-p2b-muted">{s.d}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── the honest limit ──────────────────────────────────────────── */}
      <section className={`${SHELL} border-t border-p2b-line py-14 lg:py-[72px]`}>
        <div className="grid gap-10 lg:grid-cols-12 lg:gap-12">
          <div className="lg:col-span-6">
            <h2 className="max-w-[24ch] text-[28px] font-bold leading-[1.15] tracking-[-0.022em] lg:text-[36px]">
              Not every job can be quoted from photographs.
            </h2>
            <p className="mt-5 text-[17px] leading-[1.6] text-p2b-ink-warm">
              A fault nobody can photograph, a condition behind a wall, a measurement that has to be
              right — those need somebody there, and a product that pretends otherwise hands you a
              number you cannot stand behind.
            </p>
            <p className="mt-5 text-[16px] leading-[1.6] text-p2b-muted">
              Guided Estimates is for the work you could quote from the desk if only you had the
              information. It is not an argument against site visits.
            </p>
          </div>
          <div className="lg:col-span-6">
            <div className="rounded-[3px] border border-p2b-line bg-white px-6 py-6 lg:px-7">
              <div className="text-[11px] font-bold uppercase tracking-[0.06em] text-p2b-muted-soft">
                Three ways a service can work
              </div>
              <dl className="mt-4 flex flex-col gap-4">
                {[
                  ["Instant Price", "the answers establish the scope, so your approved price is released"],
                  ["Guided Estimate", "the answers and photographs come to you, and you set the number"],
                  ["Onsite Visit", "the work has to be seen, so it is routed to a visit"],
                ].map(([n, d]) => (
                  <div key={n}>
                    <dt className="text-[15px] font-semibold text-p2b-ink">{n}</dt>
                    <dd className="mt-1 text-[15px] leading-[1.5] text-p2b-muted">{d}</dd>
                  </div>
                ))}
              </dl>
              <p className="mt-5 border-t border-p2b-line pt-5 text-[15px] leading-[1.55] text-p2b-muted">
                You choose which, service by service. None of the three is the advanced one.
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className="border-t border-p2b-line bg-p2b-canvas-alt py-14 lg:py-[72px]">
        <div className={SHELL}>
          <div className="flex flex-wrap gap-4">
            <Link
              href="/how-it-fits"
              className="rounded-full bg-p2b-accent px-6 py-3 text-[15px] font-semibold text-white"
            >
              How this fits your business
            </Link>
            <Link
              href="/product/guided-pricing"
              className="rounded-full border border-p2b-line px-6 py-3 text-[15px] font-semibold text-p2b-ink"
            >
              Where instant pricing fits
            </Link>
          </div>
        </div>
      </section>
    </main>
  );
}
