/**
 * Route Assist's domain types.
 *
 * Everything here is a plain physical/intent data shape. Route Assist may
 * preserve observable geometry and homeowner placement intent; it does not
 * diagnose hidden construction or own pricing/material/labor policy.
 */

import type {
  RouteAssistCaptureKind,
  RouteAssistConfirmationDecision,
  RouteAssistDestinationType,
  RouteAssistIncompleteReason,
  RouteAssistMode,
  RouteComplexity,
  RouteObstacle,
  RoutePhysicalTurn,
  RoutePointKind,
  RouteSurface,
} from "./taxonomy";

/**
 * A point in the single SOURCE -> DESTINATION route graph.
 * x/y are normalized 0..1 image-space coordinates, never physical distance.
 */
export type RoutePoint = {
  id: string;
  x: number;
  y: number;
  imageId: string;
  kind: RoutePointKind;
  surface?: RouteSurface | null;
  /** Set only on a WAYPOINT tagged as routing around this visible obstacle. */
  obstacle?: RouteObstacle | null;
  /**
   * Explicitly observed PHYSICAL turn geometry. Never infer this from the
   * legacy 2-D left/right turn direction on a photograph.
   */
  physicalTurn?: RoutePhysicalTurn | null;
};

/** One leg of the route, between two points already in `points`. */
export type RouteSegment = {
  id: string;
  fromPointId: string;
  toPointId: string;
  surface?: RouteSurface | null;
  /** Customer/contractor estimate for this leg alone. Never inferred from pixels. */
  estimatedLengthFt?: number | null;
  transitionAtEnd?: boolean | null;
};

/**
 * A homeowner-requested placement in the captured space.
 *
 * Placements are deliberately separate from route points. Four recessed-light
 * dots describe where four lights are wanted; they do NOT claim that the
 * electrician will wire SOURCE -> 1 -> 2 -> 3 -> 4 in that order.
 */
export type RoutePlacement = {
  id: string;
  x: number;
  y: number;
  imageId: string;
  destinationType: RouteAssistDestinationType;
  surface?: RouteSurface | null;
  label?: string | null;
};

/**
 * Evidence-only concealed-access opportunities.
 *
 * These fields say what the capture can support physically. They do not pick
 * a contractor method, promise a repair scope, or add labor/price.
 */
export type RouteAssistConcealedAccessEvidence = {
  /** Strategic openings only; never generated by a fixed holes-per-foot rule. */
  discreteOpeningsMin: number | null;
  discreteOpeningsMax: number | null;
  /** Confirmed continuous baseboard length that could provide hidden access. */
  baseboardAccessLengthFt: number | null;
  /** Visible drywall access-strip length when that path is physically supported. */
  drywallAccessStripLengthFt: number | null;
  /** Number of visible trim-assisted obstacle bypass opportunities. */
  trimAssistedBypassesCount: number;
  /** Explicit guard: another layer must choose the installation method. */
  methodSelectionAuthorized: false;
};

/** Photos and any rendered route overlays kept with the result. */
export type RouteAssistCaptureArtifacts = {
  imageIds: string[];
  overlayImageIds: string[];
};

/** A completed, confirmable Route Assist result. */
export type RouteAssistResult = {
  mode: RouteAssistMode;
  destinationType: RouteAssistDestinationType;

  points: RoutePoint[];
  segments: RouteSegment[];

  /**
   * Optional for backward compatibility with already-persisted V1 results.
   * New captures always write it.
   */
  captureKind?: RouteAssistCaptureKind;
  /** Requested fixture/device positions, independent of wiring topology. */
  placements?: RoutePlacement[];
  /** Optional evidence-only access opportunities for concealed routes. */
  concealedAccessEvidence?: RouteAssistConcealedAccessEvidence | null;

  customerConfirmedRoute: boolean;

  estimatedTotalRouteLengthFt: number | null;

  sameWall: boolean | null;

  wallTransitionsCount: number;
  insideCornersCount: number;
  outsideCornersCount: number;

  doorwayBypassesCount: number;
  windowBypassesCount: number;

  verticalTransitionsCount: number;
  wallToCeilingTransitionsCount: number;
  wallToFloorTransitionsCount: number;

  /**
   * Visible detours not already represented by doorway/window or a classified
   * transition. Kept distinct from corner counts.
   */
  visibleObstacleDetoursCount: number;

  concealedRouteComplexity: RouteComplexity | null;

  suggestedAccessOpeningsMin: number | null;
  suggestedAccessOpeningsMax: number | null;

  needsContractorReview: boolean;

  captureArtifacts: RouteAssistCaptureArtifacts;

  customerNotes: string | null;

  /** Only meaningful when `mode` is CONCEALED. */
  drywallAccessAllowed: boolean | null;
};

/** The only alternative to a complete result. */
export type RouteAssistIncomplete = {
  reason: RouteAssistIncompleteReason;
  recoveryPrompt: string;
  recovery: "RETAKE_PHOTO" | "CONTRACTOR_REVIEW";
};

export type RouteAssistOutcome = RouteAssistResult | RouteAssistIncomplete;

export function isRouteAssistIncomplete(
  outcome: RouteAssistOutcome
): outcome is RouteAssistIncomplete {
  return "reason" in outcome;
}

/** Raw capture input to `buildRouteAssistResult`. */
export type RouteAssistCaptureInput = {
  mode: RouteAssistMode;
  destinationType: RouteAssistDestinationType;
  points: RoutePoint[];
  segments: RouteSegment[];
  captureKind?: RouteAssistCaptureKind;
  placements?: RoutePlacement[];
  concealedAccessEvidence?: RouteAssistConcealedAccessEvidence | null;
  drywallAccessAllowed: boolean | null;
  captureArtifacts: RouteAssistCaptureArtifacts;
  customerNotes?: string | null;
};

/** Whole-route confirmation record. */
export type RouteAssistConfirmation = {
  decision: RouteAssistConfirmationDecision;
  decidedAt: string;
};
