/**
 * GENERATED — do not edit by hand.
 *
 * Written by scripts/capture-hero-flow.ts from a LIVE contractor catalog.
 * Every question, answer label, route and price below came out of the
 * pricing engine and the storefront's own flow API, not out of anyone's
 * head. The identity is a demonstration one; the economics are real.
 *
 * Regenerate:  npx tsx scripts/capture-hero-flow.ts
 * Check drift: npx tsx scripts/capture-hero-flow.ts --check
 */
export const HERO_FLOW = {
  "generatedBy": "scripts/capture-hero-flow.ts",
  "source": "elite-electric",
  "note": "Captured read-only from a live contractor catalog. Questions, order, answer labels, routing and prices are that contractor's; the identity shown is a demonstration one.",
  "identity": {
    "name": "Voltmark Electric",
    "shortName": "Voltmark",
    "themeFamily": "warm-welcoming",
    "themeVariant": "a",
    "themeVersion": 1
  },
  "copy": {
    "confirmAfterLook": "We'll confirm your price after a quick look"
  },
  "primary": {
    "slug": "new-120v-outlet",
    "name": "New 120V Outlet",
    "description": "A new outlet where you need one, powered from the nearest circuit. Right for everyday things — lamps, a TV, chargers, a computer. If it's for a fridge, freezer, air conditioner or anything that heats, that needs its own circuit: see Dedicated Circuit & Outlet.",
    "dto": {
      "id": "cmswc2cp9000nriwrzm7iod9z",
      "slug": "new-120v-outlet",
      "name": "New 120V Outlet",
      "bookingType": "ADJUSTED",
      "basePrice": 28000,
      "whileWeThereBasePrice": 22000,
      "startingPriceLabel": null,
      "ctaLabel": null,
      "shortDescription": "A new outlet where you need one, powered from the nearest circuit. Right for everyday things — lamps, a TV, chargers, a computer. If it's for a fridge, freezer, air conditioner or anything that heats, that needs its own circuit: see Dedicated Circuit & Outlet.",
      "icon": "new-outlet",
      "disclaimer": null,
      "estimatedMinutes": 60,
      "timeAndMaterials": null,
      "questions": [
        {
          "id": "cmt7bggu50001od5ulmqfhf6e",
          "key": "outlet_load_type",
          "prompt": "What will you be plugging in?",
          "helpText": "Some things need a circuit of their own so they can't be knocked out by whatever else is on it.",
          "inputType": "SINGLE_SELECT",
          "conditionalHelp": [],
          "order": 1,
          "options": [
            {
              "id": "cmt7bk58m0000ysajkwdnp4sz",
              "label": "Everyday things — lamps, a TV, chargers, a computer",
              "value": "everyday",
              "priceModifierCents": 0,
              "nextQuestionId": "cmt7bggwm0003od5uz89f6bsf",
              "routeAction": "CONTINUE",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": null,
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": 0,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            },
            {
              "id": "cmt7bk58m0001ysajhuakdvnu",
              "label": "A fridge, freezer, or window air conditioner",
              "value": "motor_appliance",
              "priceModifierCents": 0,
              "nextQuestionId": null,
              "routeAction": "REROUTE_SERVICE",
              "rerouteServiceId": "cmsw89z1y000rbjfc1smbgk7q",
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": "These need a circuit of their own — a fridge that shares one with something else can be switched off by it without anyone noticing.",
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": null,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            },
            {
              "id": "cmt7bk58m0002ysajykc4ogvq",
              "label": "A microwave, a space heater, or a treadmill",
              "value": "heating_appliance",
              "priceModifierCents": 0,
              "nextQuestionId": null,
              "routeAction": "REROUTE_SERVICE",
              "rerouteServiceId": "cmsw89z1y000rbjfc1smbgk7q",
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": "These draw heavily enough that sharing a circuit tends to trip it.",
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": null,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            },
            {
              "id": "cmt7bk58m0003ysajzc7m9s51",
              "label": "A compressor, a table saw, or similar shop equipment",
              "value": "shop_equipment",
              "priceModifierCents": 0,
              "nextQuestionId": null,
              "routeAction": "REROUTE_SERVICE",
              "rerouteServiceId": "cmsw89z1y000rbjfc1smbgk7q",
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": "Equipment like this draws hard when it starts up.",
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": null,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            },
            {
              "id": "cmt7bk58n0004ysajauhwseu0",
              "label": "An electric vehicle",
              "value": "ev",
              "priceModifierCents": 0,
              "nextQuestionId": null,
              "routeAction": "REROUTE_SERVICE",
              "rerouteServiceId": "cmsw8a0df003jbjfc0toxn61j",
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": "That's a different job — we'll take you to the right place.",
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": null,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            },
            {
              "id": "cmt7bk58n0005ysaj5bd9ualy",
              "label": "Something else, or I'm not sure",
              "value": "unsure",
              "priceModifierCents": 0,
              "nextQuestionId": null,
              "routeAction": "PHOTO_REVIEW",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [
                "The nameplate label on the appliance — usually a sticker on the back or underside"
              ],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": "Tell us what it is and send a photo of its label if you can find one — we'll work out what it needs and come back with a price.",
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": null,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            }
          ]
        },
        {
          "id": "cmt7bggwm0003od5uz89f6bsf",
          "key": "outlet_power_source",
          "prompt": "How would you like it powered?",
          "helpText": null,
          "inputType": "SINGLE_SELECT",
          "conditionalHelp": [],
          "order": 2,
          "options": [
            {
              "id": "cmt7bk5by0006ysaj7333sqtv",
              "label": "From the nearest outlet — from $280",
              "value": "tap_existing",
              "priceModifierCents": 0,
              "nextQuestionId": "cmsyoh0zg0008plyex3q1cdw5",
              "routeAction": "CONTINUE",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": "The quickest way, and fine for everyday things. It shares a circuit with whatever else is already on it.",
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": 0,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            },
            {
              "id": "cmt7bk5bz0007ysaj0gneicue",
              "label": "Its own circuit from the panel — from $685",
              "value": "dedicated",
              "priceModifierCents": 0,
              "nextQuestionId": null,
              "routeAction": "REROUTE_SERVICE",
              "rerouteServiceId": "cmsw89z1y000rbjfc1smbgk7q",
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": "Worth it if the outlets nearby already trip, or you'd rather this one had room to spare.",
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": null,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            }
          ]
        },
        {
          "id": "cmsyoh0zg0008plyex3q1cdw5",
          "key": "below_above_access",
          "prompt": "Is there a basement (unfinished, or with a drop ceiling) or attic directly above or below where the outlet is going?",
          "helpText": "This is what determines whether we can run the wire without opening up your walls.",
          "inputType": "SINGLE_SELECT",
          "conditionalHelp": [],
          "order": 6,
          "options": [
            {
              "id": "cmsyoh15a000dplyeoijvbsom",
              "label": "Yes",
              "value": "has_access",
              "priceModifierCents": 0,
              "nextQuestionId": "cmt31bky0000e7qam45tkloyj",
              "routeAction": "CONTINUE",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": null,
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": 0,
              "accessClassification": "ACCESSIBLE",
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            },
            {
              "id": "cmsyoh15a000eplyeimgij98v",
              "label": "No",
              "value": "no_access",
              "priceModifierCents": 0,
              "nextQuestionId": "cmsyoh115000aplyeeccgrgg7",
              "routeAction": "CONTINUE",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": null,
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": null,
              "accessClassification": "FINISHED",
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            }
          ]
        },
        {
          "id": "cmsyoh115000aplyeeccgrgg7",
          "key": "finished_space_both_sides",
          "prompt": "Is there finished living space directly above and/or below this wall, or is the room on a slab?",
          "helpText": "Either way we'd be running the wire inside the finished wall. We're checking there's nothing unusual behind it.",
          "inputType": "SINGLE_SELECT",
          "conditionalHelp": [],
          "order": 7,
          "options": [
            {
              "id": "cmtax19tv00009rewdnmxm6on",
              "label": "Yes — finished space above or below, or the room's on a slab",
              "value": "finished_both_sides",
              "priceModifierCents": 0,
              "nextQuestionId": "cmt21sizt000437pxze3e68op",
              "routeAction": "CONTINUE",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": null,
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": 0,
              "accessClassification": "FINISHED",
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            },
            {
              "id": "cmtax19tv00019rewskuerv47",
              "label": "It's an exterior wall",
              "value": "exterior_wall",
              "priceModifierCents": 0,
              "nextQuestionId": null,
              "routeAction": "PHOTO_REVIEW",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [
                "The wall where the new outlet is going, floor to ceiling",
                "A wider photo of the room"
              ],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": null,
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": null,
              "accessClassification": "UNKNOWN",
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            },
            {
              "id": "cmtax19tv00029rewr9qlcsqx",
              "label": "I'm not sure",
              "value": "unsure",
              "priceModifierCents": 0,
              "nextQuestionId": null,
              "routeAction": "PHOTO_REVIEW",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [
                "The wall where the new outlet is going, floor to ceiling",
                "A wider photo of the room"
              ],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": null,
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": null,
              "accessClassification": "UNKNOWN",
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            }
          ]
        },
        {
          "id": "cmt31bky0000e7qam45tkloyj",
          "key": "device_on_exterior_wall",
          "prompt": "Is this going on an outside wall?",
          "helpText": "A wall with the outdoors on the other side, rather than another room. It changes how we get the wire there.",
          "inputType": "SINGLE_SELECT",
          "conditionalHelp": [],
          "order": 7,
          "options": [
            {
              "id": "cmt7bgnbg000dzz5whqmkxfku",
              "label": "Yes, it's an outside wall",
              "value": "exterior",
              "priceModifierCents": 0,
              "nextQuestionId": "cmt21sj2m000637pxqciwxhvu",
              "routeAction": "CONTINUE",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": null,
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": 0,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [
                {
                  "text": "One thing about exterior walls: they're harder to route through than interior ones because of insulation and framing, and we won't know for certain until we're there. Small drywall openings may be needed to get the wiring across. If that's what it takes, it adds $125 for a run under 10 feet or $190 for a longer one, and patching and painting aren't included. We'll show you what we're looking at and confirm before doing anything.",
                  "accessClass": "ACCESSIBLE"
                }
              ],
              "components": []
            },
            {
              "id": "cmt7bgnbg000ezz5wsqi9mh3n",
              "label": "No, it's an interior wall",
              "value": "interior",
              "priceModifierCents": 0,
              "nextQuestionId": "cmt21sj2m000637pxqciwxhvu",
              "routeAction": "CONTINUE",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": null,
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": 0,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            },
            {
              "id": "cmt7bgnbg000fzz5wuxrm54xn",
              "label": "I'm not sure",
              "value": "unsure",
              "priceModifierCents": 0,
              "nextQuestionId": "cmt21sj2m000637pxqciwxhvu",
              "routeAction": "CONTINUE",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": null,
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": 0,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [
                {
                  "text": "One thing about exterior walls: they're harder to route through than interior ones because of insulation and framing, and we won't know for certain until we're there. Small drywall openings may be needed to get the wiring across. If that's what it takes, it adds $125 for a run under 10 feet or $190 for a longer one, and patching and painting aren't included. We'll show you what we're looking at and confirm before doing anything.",
                  "accessClass": "ACCESSIBLE"
                }
              ],
              "components": []
            }
          ]
        },
        {
          "id": "cmt21sizt000437pxze3e68op",
          "key": "outlet_finish_ack",
          "prompt": "Before we price this — one thing about your walls",
          "helpText": "With no attic, basement or drop ceiling to work through, the wiring for this outlet has to be fished through finished walls.\n\nYour electrician will likely need to make one or more openings in the drywall or plaster to get the cable across. We keep them small and put them where they're least visible, but on a finished wall they usually can't be avoided entirely.\n\nPatching, spackling, sanding, painting, wallpaper and trim aren't included unless we've put it in writing.\n\nThat's why we asked about attic and basement access — an open route usually means no openings at all and less time on site.",
          "inputType": "SINGLE_SELECT",
          "conditionalHelp": [],
          "order": 16,
          "options": [
            {
              "id": "cmtax0nex000kv89h0v69wbv6",
              "label": "I understand — go ahead",
              "value": "accepted",
              "priceModifierCents": 0,
              "nextQuestionId": "cmt21sj2m000637pxqciwxhvu",
              "routeAction": "CONTINUE",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": null,
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": 0,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            },
            {
              "id": "cmtax0nex000lv89h0sd2s71o",
              "label": "I'd rather Voltmark take a look first",
              "value": "review_first",
              "priceModifierCents": 0,
              "nextQuestionId": null,
              "routeAction": "PHOTO_REVIEW",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [
                "The wall where the new outlet is going, floor to ceiling",
                "The outlet or panel we'd be running the power from",
                "A wider photo of the room"
              ],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": null,
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": null,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            }
          ]
        },
        {
          "id": "cmt21sj2m000637pxqciwxhvu",
          "key": "outlet_run_distance",
          "prompt": "About how far is the new outlet from the power we'd run it from?",
          "helpText": "Roughly the path the wire would take — through the basement or attic, or across the wall — rather than the straight line across the room.",
          "inputType": "SINGLE_SELECT",
          "conditionalHelp": [],
          "order": 17,
          "options": [
            {
              "id": "cmtax0mw2000cv89ht1qa9gul",
              "label": "Less than 10 feet",
              "value": "under_10",
              "priceModifierCents": 0,
              "nextQuestionId": null,
              "routeAction": "RESOLVE_ADJUSTED",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": null,
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": null,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": [
                {
                  "quantity": 1,
                  "conditionAccessClass": "ACCESSIBLE",
                  "conditionAnswerKey": null,
                  "conditionAnswerValue": null,
                  "component": {
                    "key": "OUTLET_RUN_ACCESSIBLE_UNDER_10",
                    "customerFacingLabel": null,
                    "approvedPriceCents": 0
                  }
                },
                {
                  "quantity": 1,
                  "conditionAccessClass": "FINISHED",
                  "conditionAnswerKey": null,
                  "conditionAnswerValue": null,
                  "component": {
                    "key": "OUTLET_RUN_FINISHED_UNDER_10",
                    "customerFacingLabel": "Fishing through finished walls",
                    "approvedPriceCents": 12500
                  }
                }
              ]
            },
            {
              "id": "cmtax0mw2000dv89hpqr8umtv",
              "label": "10 to 20 feet",
              "value": "10_to_20",
              "priceModifierCents": 0,
              "nextQuestionId": null,
              "routeAction": "RESOLVE_ADJUSTED",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": null,
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": null,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": [
                {
                  "quantity": 1,
                  "conditionAccessClass": "ACCESSIBLE",
                  "conditionAnswerKey": null,
                  "conditionAnswerValue": null,
                  "component": {
                    "key": "OUTLET_RUN_ACCESSIBLE_10_20",
                    "customerFacingLabel": "Longer wiring run",
                    "approvedPriceCents": 7000
                  }
                },
                {
                  "quantity": 1,
                  "conditionAccessClass": "FINISHED",
                  "conditionAnswerKey": null,
                  "conditionAnswerValue": null,
                  "component": {
                    "key": "OUTLET_RUN_FINISHED_10_20",
                    "customerFacingLabel": "Fishing through finished walls",
                    "approvedPriceCents": 26000
                  }
                }
              ]
            },
            {
              "id": "cmtax0mw2000ev89hvoy56uvk",
              "label": "More than 20 feet",
              "value": "over_20",
              "priceModifierCents": 0,
              "nextQuestionId": null,
              "routeAction": "PHOTO_REVIEW",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [
                "The wall where the new outlet is going, floor to ceiling",
                "The outlet or panel we'd be running the power from",
                "A wider photo of the room"
              ],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": null,
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": null,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            },
            {
              "id": "cmtax0mw2000fv89hq58l7r5e",
              "label": "I'm not sure",
              "value": "unsure",
              "priceModifierCents": 0,
              "nextQuestionId": null,
              "routeAction": "PHOTO_REVIEW",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [
                "The wall where the new outlet is going, floor to ceiling",
                "The outlet or panel we'd be running the power from",
                "A wider photo of the room"
              ],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": null,
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": null,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            }
          ]
        }
      ]
    },
    "path": [
      {
        "questionKey": "outlet_load_type",
        "prompt": "What will you be plugging in?",
        "helpText": "Some things need a circuit of their own so they can't be knocked out by whatever else is on it.",
        "optionValue": "everyday",
        "optionLabel": "Everyday things — lamps, a TV, chargers, a computer"
      },
      {
        "questionKey": "outlet_power_source",
        "prompt": "How would you like it powered?",
        "helpText": null,
        "optionValue": "tap_existing",
        "optionLabel": "From the nearest outlet — from $280"
      },
      {
        "questionKey": "below_above_access",
        "prompt": "Is there a basement (unfinished, or with a drop ceiling) or attic directly above or below where the outlet is going?",
        "helpText": "This is what determines whether we can run the wire without opening up your walls.",
        "optionValue": "has_access",
        "optionLabel": "Yes"
      },
      {
        "questionKey": "device_on_exterior_wall",
        "prompt": "Is this going on an outside wall?",
        "helpText": "A wall with the outdoors on the other side, rather than another room. It changes how we get the wire there.",
        "optionValue": "exterior",
        "optionLabel": "Yes, it's an outside wall"
      },
      {
        "questionKey": "outlet_run_distance",
        "prompt": "About how far is the new outlet from the power we'd run it from?",
        "helpText": "Roughly the path the wire would take — through the basement or attic, or across the wall — rather than the straight line across the room.",
        "optionValue": "under_10",
        "optionLabel": "Less than 10 feet"
      }
    ],
    "priceCents": 28000,
    "mayNotQualify": true
  },
  "addOn": {
    "slug": "replace-standard-outlet",
    "name": "Replace Standard Outlet",
    "description": "Swapping out an existing outlet that's already there — cracked, discolored, loose, or just old — for a brand-new one in the same spot. This does NOT add a new outlet anywhere new; see \"New 120V Outlet\" for that.",
    "dto": {
      "id": "cmsw89ypa0002bjfcy2pl0l6k",
      "slug": "replace-standard-outlet",
      "name": "Replace Standard Outlet",
      "bookingType": "INSTANT",
      "basePrice": 26000,
      "whileWeThereBasePrice": 9500,
      "startingPriceLabel": null,
      "ctaLabel": null,
      "shortDescription": "Swapping out an existing outlet that's already there — cracked, discolored, loose, or just old — for a brand-new one in the same spot. This does NOT add a new outlet anywhere new; see \"New 120V Outlet\" for that.",
      "icon": "outlet",
      "disclaimer": null,
      "estimatedMinutes": 20,
      "timeAndMaterials": null,
      "questions": [
        {
          "id": "cmt1wyrkb00013zgnly64tplx",
          "key": "device_replacement_reason",
          "prompt": "Why are you replacing this?",
          "helpText": "You don't need to know what's wrong electrically — just tell us what you're seeing.",
          "inputType": "SINGLE_SELECT",
          "conditionalHelp": [],
          "order": 0,
          "options": [
            {
              "id": "cmt31ob0v0000w8ahiepc14oo",
              "label": "It works — I just want it replaced or upgraded",
              "value": "works_upgrading",
              "priceModifierCents": 0,
              "nextQuestionId": "cmsyoh0nf0001plye8pqsq1ub",
              "routeAction": "CONTINUE",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": null,
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": 0,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            },
            {
              "id": "cmt31ob0v0001w8ah630luv01",
              "label": "It stopped working",
              "value": "stopped_working",
              "priceModifierCents": 0,
              "nextQuestionId": null,
              "routeAction": "REROUTE_TROUBLESHOOTING",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": "Not sure whether the device itself has failed? That's fine — that's our job. Your electrician will remove it and test the wiring behind it. If the device is the problem, you pay the replacement price you booked and nothing more. If the power reaching it isn't right and the fault is somewhere else, we'll stop, explain what we've found, and confirm the price with you before going any further.",
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": null,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            },
            {
              "id": "cmt31ob0v0002w8ahsz60l8ig",
              "label": "It works on and off",
              "value": "intermittent",
              "priceModifierCents": 0,
              "nextQuestionId": "cmsyoh0nf0001plye8pqsq1ub",
              "routeAction": "CONTINUE",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": "Not sure whether the device itself has failed? That's fine — that's our job. Your electrician will remove it and test the wiring behind it. If the device is the problem, you pay the replacement price you booked and nothing more. If the power reaching it isn't right and the fault is somewhere else, we'll stop, explain what we've found, and confirm the price with you before going any further.",
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": 0,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            },
            {
              "id": "cmt31ob0v0003w8ahlfdhgryy",
              "label": "It's damaged, loose, cracked or worn",
              "value": "damaged",
              "priceModifierCents": 0,
              "nextQuestionId": "cmsyoh0nf0001plye8pqsq1ub",
              "routeAction": "CONTINUE",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": null,
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": 0,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            },
            {
              "id": "cmt31ob0v0004w8ahy2fer75j",
              "label": "Something's wrong beyond this one device — a burning smell, sparks, or several things dead",
              "value": "broader_problem",
              "priceModifierCents": 0,
              "nextQuestionId": null,
              "routeAction": "REROUTE_TROUBLESHOOTING",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": null,
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": null,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            },
            {
              "id": "cmt31ob0v0005w8ahcfjhlnsc",
              "label": "I'm not sure what's wrong",
              "value": "unsure",
              "priceModifierCents": 0,
              "nextQuestionId": null,
              "routeAction": "REROUTE_TROUBLESHOOTING",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": "Not sure whether the device itself has failed? That's fine — that's our job. Your electrician will remove it and test the wiring behind it. If the device is the problem, you pay the replacement price you booked and nothing more. If the power reaching it isn't right and the fault is somewhere else, we'll stop, explain what we've found, and confirm the price with you before going any further.",
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": null,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            }
          ]
        },
        {
          "id": "cmsyoh0nf0001plye8pqsq1ub",
          "key": "outlet_condition",
          "prompt": "What's happening with the outlet?",
          "helpText": null,
          "inputType": "SINGLE_SELECT",
          "conditionalHelp": [],
          "order": 1,
          "options": [
            {
              "id": "cmsyoh0pb0002plyeks6e6xcr",
              "label": "It just needs to be swapped for a new one",
              "value": "standard_swap",
              "priceModifierCents": 0,
              "nextQuestionId": null,
              "routeAction": "RESOLVE_INSTANT",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": null,
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": null,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            },
            {
              "id": "cmsyoh0pb0003plye47ltq2dl",
              "label": "It's warm, sparking, or smells like burning",
              "value": "unsafe_condition",
              "priceModifierCents": 0,
              "nextQuestionId": null,
              "routeAction": "REROUTE_TROUBLESHOOTING",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": null,
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": null,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            },
            {
              "id": "cmsyoh0pb0004plyem6ngy2ig",
              "label": "It doesn't work at all / no power",
              "value": "no_power",
              "priceModifierCents": 0,
              "nextQuestionId": null,
              "routeAction": "REROUTE_TROUBLESHOOTING",
              "rerouteServiceId": null,
              "requiredPhotoLabels": [],
              "illustrationUrls": [],
              "photoSafetyNotes": [],
              "disclaimer": null,
              "photosBlockBooking": true,
              "overrideEstimatedMinutes": null,
              "overrideTechCount": null,
              "overrideFieldLaborHours": null,
              "approvedComponentPriceCents": null,
              "accessClassification": null,
              "accessFinishedDisclaimer": null,
              "conditionalDisclaimers": [],
              "components": []
            }
          ]
        }
      ]
    },
    "path": [
      {
        "questionKey": "device_replacement_reason",
        "prompt": "Why are you replacing this?",
        "helpText": "You don't need to know what's wrong electrically — just tell us what you're seeing.",
        "optionValue": "damaged",
        "optionLabel": "It's damaged, loose, cracked or worn"
      },
      {
        "questionKey": "outlet_condition",
        "prompt": "What's happening with the outlet?",
        "helpText": null,
        "optionValue": "standard_swap",
        "optionLabel": "It just needs to be swapped for a new one"
      }
    ],
    "standaloneCents": 26000,
    "sameVisitCents": 9500,
    "mayNotQualify": true
  },
  "totalCents": 37500,
  "schedule": {
    "hours": {
      "workingDays": [
        1,
        2,
        3,
        4,
        5
      ],
      "dayStart": "08:00",
      "dayEnd": "16:30",
      "windowMinutes": 180,
      "minWindowMinutes": 60
    },
    "windows": [
      {
        "start": "8:00 AM",
        "end": "11:00 AM"
      },
      {
        "start": "11:00 AM",
        "end": "2:00 PM"
      },
      {
        "start": "2:00 PM",
        "end": "4:30 PM"
      }
    ]
  }
} as const;
