"use client";

import { useEffect, useState } from "react";
import RouteAssistRoomScanCamera, { type RouteAssistRoomScanCaptureV1 } from "@/components/route-assist/RouteAssistRoomScanCamera";
import RouteAssistSurfaceRacewayPreview from "@/components/route-assist/RouteAssistSurfaceRacewayPreview";
import { routeAssistBrowserCapturePersisterV1 } from "@/lib/visual-assist/route-assist/browserCapturePersister";
import { persistRouteAssistSweepCaptureV1, type RouteAssistSweepCaptureHandoffV1 } from "@/lib/visual-assist/route-assist/captureHandoff";
import { detectRouteAssistWebCaptureCapabilityV1, selectRouteAssistAcquisitionPathV1, type RouteAssistAcquisitionPathV1, type RouteAssistCaptureCapabilityV1 } from "@/lib/visual-assist/route-assist/captureCapability";
import { evaluateRouteAssistAutomaticCalibrationV1, resolveRouteAssistHomeownerCalibrationV1 } from "@/lib/visual-assist/route-assist/visualCalibrationFlow";

type DemoKind = "OUTLET" | "SWITCH" | "LIGHT_FIXTURE";
type RouteReviewState = "PENDING" | "ACCEPTED" | "ADJUST";
type HandoffState = "IDLE" | "UPLOADING" | "READY" | "FAILED";
type CeilingHeight = 8 | 9 | 10 | 12 | null;
const LABELS: Record<DemoKind, string> = { OUTLET: "Outlet", SWITCH: "Switch", LIGHT_FIXTURE: "Light fixture" };
const CEILING_OPTIONS: Array<{ label: string; value: CeilingHeight }> = [{ label: "8 ft", value: 8 }, { label: "9 ft", value: 9 }, { label: "10 ft", value: 10 }, { label: "12 ft", value: 12 }, { label: "Not sure", value: null }];
function destinationLabels(kind: DemoKind): string[] { if (kind === "SWITCH") return ["New switch location"]; if (kind === "LIGHT_FIXTURE") return ["New switch location", "New light fixture location"]; return ["New outlet location"]; }
function proposedRoute(kind: DemoKind): string[] { const route = ["Convert the selected existing outlet to the Wiremold starting box", "Run straight down to just above the baseboard", "Follow the baseboard/trim toward the new location", "If a doorway blocks the path, follow the side casing up, across the top casing, and down the opposite side"]; if (kind === "OUTLET") route.push("Run vertically from the baseboard to the new surface outlet box"); if (kind === "SWITCH") route.push("Run vertically from the baseboard to the new surface switch box"); if (kind === "LIGHT_FIXTURE") { route.push("Run vertically from the baseboard to the new surface switch box"); route.push("Continue the surface raceway from the switch to the new surface light-fixture box"); } return route; }

export default function RouteAssistCameraDemoPage() {
  const [kind, setKind] = useState<DemoKind>("OUTLET"); const [capture, setCapture] = useState<RouteAssistRoomScanCaptureV1 | null>(null); const [handoff, setHandoff] = useState<RouteAssistSweepCaptureHandoffV1 | null>(null); const [handoffState, setHandoffState] = useState<HandoffState>("IDLE"); const [reviewState, setReviewState] = useState<RouteReviewState>("PENDING"); const [capability, setCapability] = useState<RouteAssistCaptureCapabilityV1 | null>(null); const [acquisition, setAcquisition] = useState<RouteAssistAcquisitionPathV1 | null>(null); const [calibrationAttempted, setCalibrationAttempted] = useState(false); const [calibrationReady, setCalibrationReady] = useState(false); const [needsScaleQuestion, setNeedsScaleQuestion] = useState(false); const [ceilingHeight, setCeilingHeight] = useState<CeilingHeight>(null);
  useEffect(() => { const detected = detectRouteAssistWebCaptureCapabilityV1(); setCapability(detected); setAcquisition(selectRouteAssistAcquisitionPathV1(detected)); }, []);
  function resetCalibration() { setCalibrationAttempted(false); setCalibrationReady(false); setNeedsScaleQuestion(false); setCeilingHeight(null); }
  function chooseKind(next: DemoKind) { setKind(next); setCapture(null); setHandoff(null); setHandoffState("IDLE"); setReviewState("PENDING"); resetCalibration(); }
  async function handleCapture(next: RouteAssistRoomScanCaptureV1) { setCapture(next); setHandoff(null); setReviewState("PENDING"); resetCalibration(); if (!next.sweepFrames.length) { setHandoffState("FAILED"); return; } setHandoffState("UPLOADING"); const persisted = await persistRouteAssistSweepCaptureV1({ frames: next.sweepFrames, persister: routeAssistBrowserCapturePersisterV1 }); if (!persisted) { setHandoffState("FAILED"); return; } setHandoff(persisted); setHandoffState("READY"); if (!capability || capability.worldGeometryAvailable) { setCalibrationReady(true); return; } const automatic = evaluateRouteAssistAutomaticCalibrationV1({ capability, visualReferenceAttempted: true, references: [] }); setCalibrationAttempted(true); setNeedsScaleQuestion(automatic.decision.askHomeownerForScale); setCalibrationReady(!automatic.decision.askHomeownerForScale); }
  function answerCeilingHeight(value: CeilingHeight) { if (!capability) return; setCeilingHeight(value); const resolved = resolveRouteAssistHomeownerCalibrationV1({ capability, ceilingHeightFt: value }); const ready = resolved.usableReferences.length > 0; setCalibrationReady(ready); setNeedsScaleQuestion(!ready); }
  const canReviewRoute = handoffState === "READY" && handoff && calibrationReady;

  return <main className="min-h-screen bg-warmwhite px-4 py-6" data-testid="route-assist-camera-demo"><div className="mx-auto w-full max-w-md">
    <header className="mb-5"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-electric">Price2Book</p><h1 className="mt-1 text-2xl font-bold text-navy">Route Assist camera preview</h1><p className="mt-2 text-sm leading-6 text-slate">Ordered room-sweep capture, durable handoff, calibration, and homeowner review. No production pricing or guided flows are changed.</p></header>
    {acquisition && <div className="mb-4 rounded-xl border border-cardline bg-white p-3 text-xs leading-5 text-slate" data-testid="route-assist-acquisition-path"><strong className="text-navy">Capture path:</strong> {acquisition.path === "WORLD_GEOMETRY" ? "Measured spatial geometry" : acquisition.path === "CALIBRATED_CAMERA" ? "Camera scan with calibration" : "Contractor review"}<div>Measurement authority: {acquisition.measurementAuthority.toLowerCase()}</div></div>}
    <div className="mb-4 grid grid-cols-3 gap-2">{(Object.keys(LABELS) as DemoKind[]).map((option) => <button key={option} type="button" onClick={() => chooseKind(option)} className={`rounded-xl border px-2 py-2.5 text-xs font-semibold ${kind === option ? "border-electric bg-blue-50 text-electric" : "border-cardline bg-white text-slate"}`}>{LABELS[option]}</button>)}</div>
    {acquisition?.path === "CALIBRATED_CAMERA" && <RouteAssistRoomScanCamera key={kind} sourceLabel="Existing outlet" destinationLabels={destinationLabels(kind)} onScanComplete={handleCapture} />}
    {acquisition?.path === "REVIEW_ONLY" && <div className="rounded-xl bg-amber-50 p-4 text-sm text-amber-950">Camera evidence unavailable. Continue to contractor review rather than inventing geometry.</div>}
    {acquisition?.path === "WORLD_GEOMETRY" && <div className="rounded-xl bg-blue-50 p-4 text-sm text-navy">Calibrated spatial geometry is available; homeowner scale calibration is not required.</div>}
    {capture && handoffState === "UPLOADING" && <div className="mt-4 rounded-xl border border-cardline bg-white p-4 text-sm text-slate"><strong className="text-navy">Saving room sweep...</strong><div className="mt-1 text-xs">All {capture.sweepFrames.length} ordered frames must persist before provider analysis.</div></div>}
    {capture && handoffState === "FAILED" && <div className="mt-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-950"><strong>Room sweep could not be saved completely.</strong><div className="mt-1 text-xs">No geometry or route facts were created. Please capture the room again.</div></div>}
    {handoffState === "READY" && handoff && <div className="mt-4 rounded-xl border border-cardline bg-white p-3 text-xs text-slate" data-testid="route-assist-sweep-handoff"><strong className="text-navy">Provider media ready:</strong> {handoff.persistedFrames.length} ordered frames.<div className="mt-2 flex gap-1 overflow-x-auto">{handoff.persistedFrames.map((frame) => <img key={frame.imageId} src={frame.imageUrl} alt={`Room sweep frame ${frame.sequence + 1}`} className="h-16 w-12 shrink-0 rounded-md object-cover" />)}</div></div>}
    {handoffState === "READY" && handoff && calibrationAttempted && needsScaleQuestion && !calibrationReady && <section className="mt-4 rounded-2xl border border-cardline bg-white p-4 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-electric">One quick measurement</p><h2 className="mt-1 text-lg font-bold text-navy">About how high is your ceiling?</h2><p className="mt-2 text-sm text-slate">We couldn't find a reliable automatic size reference. Pick the height if you know it; we won't guess.</p><div className="mt-4 grid grid-cols-2 gap-2">{CEILING_OPTIONS.map((option) => <button key={option.label} type="button" onClick={() => answerCeilingHeight(option.value)} className="rounded-xl border border-cardline px-3 py-3 text-sm font-semibold text-navy">{option.label}</button>)}</div>{ceilingHeight === null && <p className="mt-3 text-xs text-slate">Not sure keeps the route unmeasured and should send the job to contractor review.</p>}</section>}
    {canReviewRoute && <section className="mt-4 overflow-hidden rounded-2xl border border-cardline bg-white shadow-sm"><div className="border-b border-cardline p-4"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-electric">Proposed Wiremold route</p><h2 className="mt-1 text-lg font-bold text-navy">Does this route look right?</h2><p className="mt-2 text-sm text-slate">The complete sweep is durably saved. Geometry analysis still has to establish the actual path.</p></div><div className="p-4"><img src={handoff.reviewImage.imageUrl} alt="Room sweep review scene" className="mb-4 aspect-[4/3] w-full rounded-xl object-cover" /><RouteAssistSurfaceRacewayPreview destinationKind={kind} /><div className="mt-4 rounded-xl bg-blue-50 p-3 text-sm text-navy"><strong>Starting from this existing outlet</strong><div className="mt-1 text-xs text-slate">This outlet becomes the Wiremold starting box.</div></div><ol className="mt-4 space-y-3">{proposedRoute(kind).map((step, index) => <li key={step} className="flex gap-3 text-sm text-slate"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-navy text-xs font-bold text-white">{index + 1}</span><span>{step}</span></li>)}</ol><div className="mt-4 rounded-xl border border-cardline bg-slate-50 p-3 text-xs text-slate"><strong className="text-navy">Provider handoff:</strong> {handoff.captureArtifacts.imageIds.length} durable ordered image IDs. Distance remains unresolved until validated geometry evidence exists.</div>{reviewState === "PENDING" && <div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={() => setReviewState("ADJUST")} className="rounded-xl border border-cardline px-3 py-3 text-sm font-semibold text-navy">Adjust route</button><button type="button" onClick={() => setReviewState("ACCEPTED")} className="rounded-xl bg-electric px-3 py-3 text-sm font-semibold text-white">Looks good</button></div>}{reviewState === "ACCEPTED" && <div className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">Review checkpoint only; pricing and material quantities remain untouched.</div>}{reviewState === "ADJUST" && <div className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-950">Route adjustment requested. Geometry must be corrected and shown again.<button type="button" onClick={() => setReviewState("PENDING")} className="mt-2 block text-xs font-semibold underline">Return to review</button></div>}</div></section>}
    <p className="mt-4 text-center text-xs text-slate-light">No hidden wiring inference, materials, labor, price, onboarding, or decision-tree behavior is changed here.</p>
  </div></main>;
}
