/**
 * Capture the homeowner demo shown on the marketing site — ADR-020.
 *
 * WHY A SNAPSHOT AND NOT A MOCK-UP
 *
 * The homepage claims the product asks the questions that change the price and
 * then decides whether the job may be booked. A hand-written demo of that is a
 * drawing of the claim, and drawings drift from the thing they describe.
 *
 * So every screen the demo shows is generated by walking a real service's real
 * question tree and calling the SAME resolveRoute the storefront calls, for
 * EVERY path through the tree. The prices are what the pricing engine
 * computes; the "we'll price this" and "this needs review" outcomes are what
 * the resolver decides. Nothing here is authored by hand except the search
 * phrasing a homeowner would type.
 *
 * The result is committed as data, so the marketing page needs no database, no
 * tenant, and can take no booking. Regenerate it the way screenshots are
 * regenerated — one command — whenever the underlying service changes.
 *
 *   npx tsx scripts/demo-contractor.ts --create
 *   npx tsx scripts/capture-demo-flow.ts
 *   npx tsx scripts/demo-contractor.ts --destroy
 */
import { PrismaClient } from "@prisma/client";
import { writeFileSync } from "node:fs";
import { loadServiceForResolution, loadPricingSettings, resolveRoute } from "../lib/routeResolver";
import { keywordFallback } from "../lib/serviceMatch";
import { DEMO } from "./demo-contractor";

const prisma = new PrismaClient();

/** The service the demo walks. Chosen for a tree a homeowner can answer. */
const SERVICE_KEY = process.argv.includes("--service")
  ? process.argv[process.argv.indexOf("--service") + 1]
  : "soundbar-installation";

const OUT = "components/marketing/demoFlow.ts";

/** What a homeowner types, versus what the service is called. */
/**
 * What a homeowner types, versus what the service is called.
 *
 * Checked against the real matcher rather than chosen for how it reads —
 * "mount my soundbar below the television" comes back `unsure`, this one comes
 * back `suggestion`. The demo should show the matcher succeeding, and the only
 * way to know which phrasings do is to ask it.
 */
const SEARCH_QUERY = process.argv.includes("--query")
  ? process.argv[process.argv.indexOf("--query") + 1]
  : "I bought a soundbar and need it mounted under my TV";

type Option = {
  value: string;
  label: string;
  disclaimer: string | null;
  /** The question this answer leads to, when it leads anywhere. */
  next: string | null;
};
type Step = { key: string; prompt: string; helpText: string | null; options: Option[] };
type Outcome =
  | { status: "PRICED"; priceCents: number; disclaimers: string[]; photoLabels: string[] }
  | { status: "REVIEW"; reason: string; photoLabels: string[] }
  /** The answers describe a different job. The product says so instead of pricing this one. */
  | { status: "REROUTE"; targetName: string; targetKey: string | null }
  | { status: "OTHER"; status_: string };

/**
 * Which services would actually make a good demo?
 *
 * A demo is only worth running if the tree can end in more than one place. A
 * service where every path prices cleanly cannot show the product declining to
 * price something, which is half the story — so this reports the real split
 * for every candidate rather than leaving the choice to intuition about which
 * job "feels" representative.
 */
async function survey(contractorId: string) {
  const rows = await prisma.service.findMany({
    where: { contractorId, active: true, questions: { some: {} } },
    select: { id: true, name: true, templateKey: true },
  });
  const settings = await loadPricingSettings(prisma, contractorId);
  if (!settings) throw new Error("no pricing settings");

  console.log(`\n  ${"template key".padEnd(30)} ${"Q".padStart(2)} ${"paths".padStart(5)} ${"priced".padStart(6)} ${"review".padStart(6)}  outcome                 prices`);
  for (const r of rows) {
    const svc = await loadServiceForResolution(prisma, r.id);
    if (!svc) continue;
    const byId = new Map(svc.questions.map((q) => [q.id, q]));
    let priced = 0, review = 0, other = 0;
    // Distinct prices matter as much as the priced/review split: the section
    // this demo sits under is called "Ask the questions that change the
    // price", and a tree whose answers never move the number cannot show it.
    const prices = new Set<number>();
    const walk = (key: string | null, answers: Record<string, string>) => {
      if (!key) {
        const route = resolveRoute(svc, answers, true, settings);
        if (route.status === "PRICED") { priced++; prices.add(route.priceCents); }
        else if (route.status === "REVIEW") review++;
        else other++;
        return;
      }
      const q = svc.questions.find((x) => x.key === key);
      if (!q) return;
      for (const o of q.options) {
        walk(o.routeAction === "CONTINUE" && o.nextQuestionId ? byId.get(o.nextQuestionId)?.key ?? null : null,
             { ...answers, [q.key]: o.value });
      }
    };
    walk(svc.questions[0]?.key ?? null, {});
    const total = priced + review + other;
    const both = priced > 0 && review > 0;
    const varies = prices.size > 1;
    const flag = both && varies ? "✓✓ both + price varies" : both ? "✓  both, one price" : priced === 0 ? "   never prices" : "   always prices";
    const money = [...prices].sort((a, b) => a - b).map((c) => `$${Math.round(c / 100)}`).join("/");
    console.log(`  ${(r.templateKey ?? "?").padEnd(30)} ${String(svc.questions.length).padStart(2)} ${String(total).padStart(5)} ${String(priced).padStart(6)} ${String(review).padStart(6)}  ${flag.padEnd(23)} ${money}`);
  }
  console.log();
}

async function main() {
  const contractor = await prisma.contractor.findUnique({
    where: { slug: DEMO.slug },
    select: { id: true, name: true },
  });
  if (!contractor) {
    console.error(`\n  No demo contractor. Run: npx tsx scripts/demo-contractor.ts --create\n`);
    process.exit(1);
  }

  if (process.argv.includes("--survey")) {
    await survey(contractor.id);
    await prisma.$disconnect();
    return;
  }

  const row = await prisma.service.findFirst({
    where: { contractorId: contractor.id, templateKey: SERVICE_KEY },
    select: { id: true, name: true, shortDescription: true },
  });
  if (!row) {
    console.error(`\n  ${SERVICE_KEY} is not in the demo contractor's catalog.\n`);
    process.exit(1);
  }

  const settings = await loadPricingSettings(prisma, contractor.id);
  if (!settings) throw new Error("the demo contractor has no pricing settings");

  const nameById = new Map(
    (await prisma.service.findMany({ where: { contractorId: contractor.id }, select: { id: true, name: true, templateKey: true } }))
      .map((x) => [x.id, { name: x.name, key: x.templateKey }]),
  );

  /**
   * Capture one service's tree and the outcome of every path through it.
   *
   * Returns the reroute targets it found, so the caller can capture those too.
   * The product's rule is "no dead ends" — an answer showing the customer
   * picked the wrong service sends them to the right one, carrying their
   * answers. A demo that stops at the reroute misrepresents that as a refusal.
   */
  async function captureFlow(serviceId: string) {
    const svc = await loadServiceForResolution(prisma, serviceId);
    if (!svc) throw new Error(`service ${serviceId} vanished between queries`);
    const meta = await prisma.service.findUniqueOrThrow({
      where: { id: serviceId },
      select: { name: true, shortDescription: true, templateKey: true },
    });
    const byId = new Map(svc.questions.map((q) => [q.id, q]));
    const nextKey = (o: { routeAction: string; nextQuestionId: string | null }) =>
      o.routeAction === "CONTINUE" && o.nextQuestionId ? byId.get(o.nextQuestionId)?.key ?? null : null;

    const steps: Step[] = svc.questions.map((q) => ({
      key: q.key,
      prompt: q.prompt,
      helpText: q.helpText,
      options: q.options.map((o) => ({
        value: o.value, label: o.label, disclaimer: o.disclaimer, next: nextKey(o),
      })),
    }));

    const outcomes: Record<string, Outcome> = {};
    const targets = new Set<string>();
    const walk = (key: string | null, answers: Record<string, string>) => {
      if (!key) {
        const route = resolveRoute(svc, answers, true, settings!);
        const k = JSON.stringify(answers);
        if (route.status === "PRICED") {
          outcomes[k] = { status: "PRICED", priceCents: route.priceCents, disclaimers: route.disclaimers, photoLabels: route.photoLabels };
        } else if (route.status === "REVIEW") {
          outcomes[k] = { status: "REVIEW", reason: route.reason, photoLabels: route.photoLabels };
        } else if (route.status === "REROUTE") {
          const t = nameById.get(route.targetServiceId);
          targets.add(route.targetServiceId);
          outcomes[k] = { status: "REROUTE", targetName: t?.name ?? "another service", targetKey: t?.key ?? null };
        } else {
          outcomes[k] = { status: "OTHER", status_: route.status };
        }
        return;
      }
      const q = svc.questions.find((x) => x.key === key);
      if (!q) return;
      for (const o of q.options) walk(nextKey(o), { ...answers, [q.key]: o.value });
    };
    walk(steps[0]?.key ?? null, {});

    return {
      flow: { key: meta.templateKey, name: meta.name, description: meta.shortDescription, steps, outcomes },
      targets: [...targets],
    };
  }

  const flows: Record<string, unknown> = {};
  const primary = await captureFlow(row.id);
  flows[primary.flow.key ?? "primary"] = primary.flow;

  // One level of reroute targets. A target that reroutes onward is rare and
  // would make the demo a maze; the second hop says so instead of pretending.
  for (const targetId of primary.targets) {
    const t = await captureFlow(targetId);
    if (t.flow.key) flows[t.flow.key] = t.flow;
    console.log(`  + reroute target captured: ${t.flow.name} (${t.flow.steps.length} questions)`);
  }

  /**
   * The search step, answered by the REAL matcher.
   *
   * keywordFallback is the same function the storefront falls back to when the
   * language model is unavailable, so what the demo shows for a homeowner's
   * phrasing is what the product would actually do with it — including, if it
   * happens, being unsure.
   */
  const catalog = await prisma.service.findMany({
    where: { contractorId: contractor.id, active: true },
    select: { slug: true, name: true, contractorCategory: { select: { canonicalCategory: { select: { slug: true } } } } },
  });
  const match = keywordFallback(
    SEARCH_QUERY,
    catalog.map((c) => ({
      slug: c.slug,
      name: c.name,
      categorySlug: c.contractorCategory?.canonicalCategory?.slug ?? "",
    })),
  );
  console.log(`  search "${SEARCH_QUERY}" -> ${match.kind}`);

  // Same-visit work: the contractor's own approved add-on prices.
  const addOns = await prisma.service.findMany({
    where: {
      contractorId: contractor.id,
      active: true,
      whileWeThereBasePrice: { not: null },
      id: { not: row.id },
    },
    orderBy: { whileWeThereBasePrice: "asc" },
    select: { name: true, whileWeThereBasePrice: true },
    take: 3,
  });

  const hours = await prisma.businessHours.findUnique({
    where: { contractorId: contractor.id },
    select: { dayStart: true, dayEnd: true, windowMinutes: true },
  });

  const snapshot = {
    // Recorded so a reader can tell at a glance that this is not hand-written,
    // and can regenerate it.
    generatedBy: "scripts/capture-demo-flow.ts",
    contractor: contractor.name,
    note: "A demonstration contractor. Every price and routing decision below was produced by the real pricing engine and route resolver.",
    search: {
      query: SEARCH_QUERY,
      serviceName: row.name,
      // Recorded so the page can say the match came from the matcher.
      matchKind: match.kind,
    },
    /** Which flow the demo starts in. */
    primary: primary.flow.key,
    /** Every flow the demo can reach, including reroute destinations. */
    flows,
    addOns: addOns.map((a) => ({ name: a.name, priceCents: a.whileWeThereBasePrice! })),
    schedule: {
      dayStart: hours?.dayStart ?? "08:00",
      dayEnd: hours?.dayEnd ?? "16:30",
      windowMinutes: hours?.windowMinutes ?? 180,
    },
  };

  // A TS module rather than JSON: typed at the import site, and no
  // resolveJsonModule needed to read it from a component.
  writeFileSync(
    OUT,
    `/**\n` +
      ` * GENERATED — do not edit by hand.\n` +
      ` *\n` +
      ` * Written by scripts/capture-demo-flow.ts by walking a real service's real\n` +
      ` * question tree and resolving EVERY path with the same resolveRoute the\n` +
      ` * storefront calls. Every price and every routing decision below came out of\n` +
      ` * the pricing engine, not out of somebody's head.\n` +
      ` *\n` +
      ` * Regenerate:\n` +
      ` *   npx tsx scripts/demo-contractor.ts --create\n` +
      ` *   npx tsx scripts/capture-demo-flow.ts --service ${SERVICE_KEY}\n` +
      ` *   npx tsx scripts/demo-contractor.ts --destroy\n` +
      ` */\n` +
      `export const DEMO_FLOW = ${JSON.stringify(snapshot, null, 2)} as const;\n`,
  );

  console.log(`\n  ${row.name}`);
  for (const [key, f] of Object.entries(flows)) {
    const o = Object.values((f as any).outcomes) as Outcome[];
    const n = (st: string) => o.filter((x) => x.status === st).length;
    console.log(`    ${String(key).padEnd(30)} ${(f as any).steps.length}Q  ${o.length} paths  ${n("PRICED")} priced, ${n("REVIEW")} review, ${n("REROUTE")} reroute`);
  }
  console.log(`  ${addOns.length} same-visit add-ons`);
  console.log(`  -> ${OUT}\n`);

  await prisma.$disconnect();
}

main().catch(async (e) => { console.error(e); await prisma.$disconnect(); process.exit(1); });
