import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { ELECTRICAL_CORE_CALIBRATION_SCENARIOS } from "../lib/electrical/laborCalibrationWizard";

let checks = 0;
const ok = (condition: unknown, message: string) => { assert.ok(condition, message); checks += 1; };
const read = (relative: string) => fs.readFileSync(path.join(process.cwd(), relative), "utf8");

const page = read("app/dashboard/setup/page.tsx");
const panel = read("app/dashboard/setup/AtomicLaborWizardPanel.tsx");
const route = read("app/api/portal/labor-calibration/route.ts");
const directQueue = read("lib/electrical/laborDirectEntryQueue.ts");

ok(ELECTRICAL_CORE_CALIBRATION_SCENARIOS.length === 8, "setup uses exactly eight core calibration scenarios");
ok(page.includes("AtomicLaborWizardPanel"), "pricing foundation renders the atomic wizard");
ok(!page.includes('from "./LaborWizardPanel"') && !page.includes("resolveTaskEligibility"), "pricing foundation no longer loads the three-task service wizard");
ok(page.includes("contractorLaborScenarioAnswer.findMany"), "saved scenario evidence is loaded for resume");
ok(panel.includes("Question {index + 1} of {scenarios.length}"), "wizard presents one bounded question at a time with a truthful dynamic total");
ok(page.includes("offeredServiceSlugs={offeredLaborServiceSlugs}"), "setup passes only the contractor's offered service set into specialty selection");
ok(panel.includes("selectElectricalTargetedCalibrationScenarios"), "wizard appends targeted specialty questions through the guarded selector");
ok(panel.includes("Based on a specialty service you offer"), "wizard explains why an additional targeted question appears");
ok(panel.includes("Published-book starting point") && panel.includes("publishedBookStartingPoint"), "wizard prominently shows the calculated book starting point");
ok(panel.includes("your actual in-field time may be different") && panel.includes("Enter the time that is typical for you"), "wizard clearly separates published suggestion from contractor reality");
ok(panel.includes('kind: "scenario-answers"'), "wizard saves scenario evidence rather than service values");
ok(panel.includes('kind: "operation-decisions"'), "review saves explicitly selected atomic decisions through the separate boundary");
ok(panel.includes("Nothing is preselected"), "operation proposals are opt-in rather than silently accepted");
ok(panel.includes("selectedOperations.has(proposal.operationKey)"), "only contractor-selected operation rows are submitted");
ok(panel.includes("Next labor units needed by your services") && panel.includes("buildElectricalLaborDirectEntryQueue"), "wizard offers a bounded direct-entry completion queue after scenario review");
ok(panel.includes(".slice(0, 12)"), "direct-entry completion is capped to a manageable batch");
ok(panel.includes("Used by {entry.affectedServiceSlugs.length} offered"), "each direct unit explains its offered-service impact");
ok(panel.includes("scenarioKeys: []") && panel.includes('source: "DIRECT"'), "manual atomic units persist with explicit direct-entry provenance rather than fabricated scenario evidence");
ok(directQueue.includes("b.affectedServiceSlugs.length - a.affectedServiceSlugs.length"), "completion queue prioritizes operations by offered-service unlock impact");
ok(panel.includes("setSavedDecisionKeys") && panel.includes("remaining highest-impact work are updated below"), "a successful partial save advances the queue in place without requiring a page reload");
ok(panel.includes("setDirectEntryMinutes({})") && panel.includes("setSelectedOperations(new Set())"), "saved batch inputs are cleared before the next batch is shown");
ok(panel.includes("editedOperationMinutes") && panel.includes("Number(entered) / 60"), "suggested operation edits use contractor-facing minutes while persisting canonical hours");
ok(panel.includes("Minutes per ${proposal.unit}") && panel.includes("min/{proposal.unit}"), "proposal and direct-entry controls use the same visible time unit");
ok(panel.includes("returnToReviewAfterEdit") && panel.includes("setReturnToReviewAfterEdit(true)"), "editing one reviewed scenario returns to review instead of replaying later questions");
ok(!panel.includes("Review again"), "review no longer offers a misleading full replay control beside per-answer edits");
ok(panel.includes("invalidatedOperationKeys") && panel.includes("!invalidated.has(key)"), "changed scenario evidence immediately removes reopened proposal decisions from client progress");
ok(panel.includes("router.refresh()"), "scenario changes refresh server-derived service labor after invalidation");
ok(panel.includes("required labor units saved") && panel.includes("modeled offered services have all of their atomic labor units"), "wizard reports unit and offered-service operation coverage separately");
ok(panel.includes("Route measurements and service approval are still separate"), "operation completion is not mislabeled as pricing readiness");
ok(!panel.includes("setDone"), "partial save no longer dead-ends behind a terminal success screen");
ok(panel.includes("if (firstMissing === -1) setEvidenceSaved(true)"), "a returning contractor with complete scenario evidence resumes directly at operation work");
ok(panel.includes("Review scenario answers"), "returning contractor can deliberately reopen evidence review without being forced through it");
ok(panel.includes("useRouter") && panel.includes("router.refresh()"), "successful atomic save refreshes the server-derived service review without approving it");
ok(!panel.includes("fieldLaborHours") && !route.includes("fieldLaborHours"), "new wizard and endpoint cannot write whole-service labor");
ok(!panel.includes("basePrice") && !route.includes("basePrice"), "new wizard and endpoint cannot publish a price");
ok(route.includes("db.$transaction"), "each calibration batch is transactional");
ok(panel.includes("Nothing is copied into a service or customer price automatically"), "contractor sees the no-auto-publish boundary before starting");
ok(panel.includes("supporting evidence only—not an automatic multiplier"), "speed signal is presented as supporting evidence only");

console.log(`ATOMIC LABOR WIZARD CONTRACT — ${checks}/${checks} checks passed`);
